baseURL = 'https://thus-chains.github.io/'
languageCode = 'en-us'
title = 'CHAINS'
theme = 'ananke'

[menu]
    [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

    [[menu.main]]
    identifier = "members"
    name = "Members"
    url = "/members/"
    weight = 2

    [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = 3

    [[menu.main]]
    identifier = "news"
    name = "News"
    url = "/news/"
    weight = 4